# Generated by Django 5.0.4 on 2024-05-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(max_length=100)),
                ('emp_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('last_working_date', models.DateField()),
                ('reporting_management_id', models.CharField(max_length=100)),
                ('reporting_manager_name', models.CharField(max_length=255)),
                ('project_released_feedback', models.TextField()),
                ('pmo', models.CharField(max_length=255)),
                ('pmo_name', models.CharField(max_length=255)),
                ('pmo_email', models.EmailField(max_length=254)),
                ('talent_central_contact_name', models.CharField(max_length=255)),
                ('talent_central_contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
