# Generated by Django 5.0.4 on 2024-05-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_project_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='emp_name',
            new_name='Emp_name',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='last_working_date',
            new_name='Last_working_date',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='pmo',
            new_name='PMO',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='pmo_email',
            new_name='PMO_email',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='pmo_name',
            new_name='PMO_name',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='project_name',
            new_name='Project_name',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='project_released_feedback',
            new_name='Project_released_feedback',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='reporting_management_id',
            new_name='Reporting_management_id',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='reporting_manager_name',
            new_name='Reporting_manager_name',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='talent_central_contact_email',
            new_name='Talent_central_contact_email',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='talent_central_contact_name',
            new_name='Talent_central_contact_name',
        ),
    ]
