# Generated by Django 5.0.4 on 2024-05-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_project_management', '0002_rename_emp_name_employeedetails_emp_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='Reporting_management_id',
            new_name='Reporting_manager_id',
        ),
    ]
